### PR TITLE
feat: Add landing page

### PR DESCRIPTION
**Pull request by anishkny**
Create a landing page (index.html) to show added adjectives.

Demo: https://anishkny.github.io/SomethingNice/

### CODE REVIEW

**Comment by anishkny** [comment]
hi @comentarinformal the [build failure](https://travis-ci.com/comentarinformal/SomethingNice/builds/88892886) is expected.

Please add a `GITHUB_TOKEN` environment variable in TravisCI settings so that changes can be pushed to this repo's `gh-pages` branch. See [instructions](https://docs.travis-ci.com/user/deployment/pages/#setting-the-github-token).

**Comment by comentarinformal** [comment]
Oh, I see! I thought it was auto-poblated by logging in via Github account.

**Comment by anishkny** [comment]
In an ideal world right 😉 Its pretty straight forward, I have done it in the past for some of my repos...

**Comment by anishkny** [comment]
Sweet looks like it worked!

https://comentarinformal.github.io/SomethingNice/

**Pull request merged**
